### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Moelf** [akio-tomiya/LatticeQCD.jl#31]
It looks like the Fortran code you reference is GPL based,which probably means this package has to be GPL as well

**Comment by akio-tomiya** [comment]
Thanks for mentioning it. 

We did not translate the code into Julia but refer algorithms. Our code is written in Julia-ish way.
Moreover, algorithms in the code are very standard in lattice QCD community. 

So we do not think our code is a derivative of the existing code, and our code is not covered by GPL.
