### ISSUE TITLE
Confusions on LatticeQCD.jl/src/system/lqcd.jl, line 79

### ISSUE THREAD

**Issue by YtihalX** [akio-tomiya/LatticeQCD.jl#57]
When trying  different measurements of plaquette, I found that the variable `i_plaq` in the function `run_LQCD_file` never changes. Let's say we have the `measurements_methods` as 
[
  {"hasclover" : false, "Clover_coefficient" : 1.5612, 
   "r" : 1.0, "Dirac_operator" : "Wilson", 
   "hop" : 0.141139, "measure_every" : 1, 
   "methodname" : "Pion_correlator"},
  {"methodname" : "Polyakov_loop",},
  {"methodname" : "Plaquette",},
]
(not the  struct `Measuremet_methods`, but rather the field extracted from the `System_parameters.Params`)
so from line 78-83 the `i_plaq` should be changed to, say, 3. But this assignment never happened, cause the condition `typeof(measurements.measurements[i]) == Plaquette_measurement` never met, so I wonder maybe the correct code should be like `if isa(measurements.measurements[i], Plaquette_measurement)` otherwise the `typeof(measuremets.measurements[i])` could never match this generic type.

**Comment by cometscome** [comment]
Thank you for giving us comments. I checked it and you are right. I modified the code in lqcd.jl.
